-- Portfolio visitor analytics. Applied to project xidxcafcdfmoxxvnjjkl.
-- Public visitors can only call track_analytics_event; raw events are admin-only.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view','project_open','image_open','cv_open','contact_click')),
  session_id uuid not null,
  project_id uuid null,
  project_title text not null default '',
  page_path text not null default '/',
  referrer_host text not null default '',
  device_type text not null default 'desktop' check (device_type in ('mobile','tablet','desktop')),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_type_created_idx on public.analytics_events (event_type, created_at desc);
create index if not exists analytics_events_project_created_idx on public.analytics_events (project_id, created_at desc);
create index if not exists analytics_events_session_created_idx on public.analytics_events (session_id, created_at desc);

alter table public.analytics_events enable row level security;

create policy analytics_admin_read on public.analytics_events
  for select to authenticated
  using (auth.uid() = 'eb549008-aaa8-43d8-a7b3-a8feb3acd167'::uuid);

revoke all on public.analytics_events from anon;
revoke all on public.analytics_events from authenticated;
grant select on public.analytics_events to authenticated;

-- The tracking and dashboard RPC functions are managed through Supabase migrations.
